[alias]
serve = ["watch", "-c", "-q", "--no-ignore", "-i", "target", "-w", "src", "-w", ".env", "-w", "src/resources", "-x", "run"]
rb = ["run", "-q", "--bin", "rustbasic-cli", "--"]
rustbasic = ["run", "-q", "--bin", "rustbasic-cli", "--"]
